### PR TITLE
allow debounce/multi/hold times to be configurable

### PR DESCRIPTION
**Pull request by sumnerboy12**
Implements #17

### CODE REVIEW

**Comment by sumnerboy12** [comment]
@moinmoin-sh I think we will need this change, based on what Frank has been seeing - I get the feeling a lot of people will need the ability to tweak these times depending on what switches they are using. It does blow the memory on the Uno for 6x MCPs which is a shame, but I think it a necessary change. 

Would you agree?

**Comment by moinmoin-sh** [comment]
Here are some points regarding configurable debouncing:
During my testing the last days I found out that it's not easy to set an appropriate timing for debouncing. Without the ability to measure it's a trial and error process. Even with measuring the button input with a scope is not really satisfying, because the analog measure with the scope says nothing about what the signal looks like after being digitized by the MCP and finally what the USM SW saw. Users who are able to manage that, shouldn't have a problem to find the appropriate lines in USM_input.h. And it belongs to the USM_input lib, so why not configure it there?
Unfortunately the setting of (larger) debounce times effects ALL inputs. Especially with large debounce times that is not desireable because the multi click sensitivity is effected.
In my opinion configurable debounce times as you proposed (spending a lot of RAM) only makes sense, if it would be configurable per input which would allow to add special handling for single (poor) buttons/switches. Furthermore it might be necessary to limit these single inputs to single click detection because with that bouncing switches multi clicks will never work reliable.
Back to your question , do I agree ? 
No if just spending the RAM to have it in config.h, but yes if the functionality  is expanded as desribed above.

**Comment by sumnerboy12** [comment]
I have been thinking as well, and came to the same conclusion re. debounce
times being to be configurable per input.

We could initially set sensible defaults depending on the input type, i.e.
shorter times for buttons, longer for switch and toggles.

This would likely make things better for those using simple switch or
toggle inputs but we may need a new type to support single click buttons,
i.e. without multi click support.

All these could then have longer debounce times without effecting multi
click support for other inputs with high quality buttons.

**Comment by sumnerboy12** [comment]
Have implemented https://github.com/SuperHouse/LSC/pull/26 which will hopefully be sufficient without needing the over complication of supporting specific debounce times per input.

**Pull request closed without merging**
