### PR TITLE
add support for TIMER type

### PR DESCRIPTION
**Pull request by sumnerboy12**
NOTE: this change blows out the memory for an Uno - you can only run safely with `MAX_MCP_COUNT = 3` in `config.h`. You really need something bigger to run this firmware now.

### CODE REVIEW

**Comment by sumnerboy12** [comment]
This won't be merged in the short-term, since it will cause those with Unos to have memory problems. Once the rack controllers are available, with ESP32s or Megas2, and we don't have memory constraints this new feature can be merged to `main`.

**Comment by sumnerboy12** [comment]
@moinmoin-sh I can't seem to add you as a reviewer - but if you are interested feel free to run your eye over this :)

**Comment by moinmoin-sh** [comment]
I downloaded your new version and took a look. Of course it works, but this time I need to put the pedantic hat on.

This reminds me on the old days "staircase lightning automats" (don't know the correct English wording). Is this really something that showld go into a switch controller? In my opinion this is a function that can be much better handled in the home automation system by taking additional environment conditions like time, darkness ... into account.

Secondly I don't think such function belongs to a USM, because it's not something that relates to a switch. All previous enhancements that you integrated are only taking different types of switches into account and made them available - without knowing anything about what shall be turned on/off or whatever. This timer function to me belongs to an output device. Like said before a light that should be on for a certain time, a heater, an alrm .. whatever. So if you what to include a timer function out of the Homeautomation it should be part of an output controlller , like a URC  (Universal Relay Controller) . A firmware that needs to be written to control a relay driver board for example.
Not easy for me to write down my thoughts but I hope you get my point ?

**Comment by sumnerboy12** [comment]
I understand exactly what you are saying @moinmoin-sh and I agree. I have no intention of using this in my own system, I would always put this sort of timing logic in my central rules engine or logic controller. It was a request from FrankMc on the Discord server, who wanted to use the USM and URC without any logic in the middle. 

I could see the value in that, for the simple use-case. But thought it was easiest to add the logic into the USM, since we are already timing various things when processing input events. Adding a simple `TIMER` type was an easy extension to this.

But I take your point, and agree in-principle, that this sort of logic belongs in the output controller. To be honest, I was just keen to see how easy it would be to extend the USM to support this - and decided to do it!

I will close the PR as it was also causing issues with memory limits on the Uno. Thanks for your considered and detailed thoughts on the matter!

**Pull request closed without merging**
